### ISSUE TITLE
Implement IGE mode for AES

### ISSUE THREAD

**Issue by cosmonawt** [somesocks/lua-lockbox#10]
I want to build a framework for [MtProto](https://core.telegram.org/mtproto), the communucation protocol used by Telegram, and this library is the most promising in regards to including all the encryption mechanism I need. However AES IGE is missing. Any chance you will implement this as well?

**Comment by somesocks** [comment]
Lucky for you, I had some free time today.
IGE is added with a few test cases.  Check the linked article in the commit message for details about X0, Y0, and the IV order.
Let me know if it works.

**Comment by cosmonawt** [comment]
Thank you very much, I will check it out as soon as I have time.
