### ISSUE TITLE
Addon release for a game

### ISSUE THREAD

**Issue by haaax2000** [somesocks/lua-lockbox#21]
Would you mind if I released this library (not the whole library) as a workshop addon for a game - namely Garry's Mod? Giving you 99% credit of course (requires a bit of modification so it works with the game) and if you have a Steam account I'd add you as an author

**Comment by tst2005** [comment]
Hello,
You just need to follow the condition of the lockbox [LICENSE](https://github.com/somesocks/lua-lockbox/blob/master/LICENSE).
If I'm not wrong with the MIT License, you can do what you want (even sell it!) if you preserve the License content and the Copyright mention.
Regards,

**Comment by haaax2000** [comment]
I see, thank you
