### ISSUE TITLE
Is lockbox still looking for maintainers? I'd like to volunteer as a collaborator.

### ISSUE THREAD

**Issue by greatwolf** [somesocks/lua-lockbox#26]
There's some refactors, improvements and optimizations I'd like to contribute to upstream. Also looking to implement sha2_384 and sha2_512 to complement lockbox as well as fixing up and merging in tst's Salsa20 implementation.

**Comment by tst2005** [comment]
The [salsa20](https://github.com/mrogaski/lua-salsa20) code is not my work. I just found it. It is the code and repository for [mrogaski](https://github.com/mrogaski/).

I also found some lockbox-like project :
- https://github.com/philanc/plc (for lua5.3+ only)
- https://github.com/user-none/lua-hashings (lot of hash, only hash)

I dreams of an universal unified crypto lib...

**Comment by greatwolf** [comment]
kewl, yea I came across those 2 libraries too. plc looks quite promising and I like the way the code looks.

lua-hashings I also looked at, really didn't like the design of it. Two major issues with it:

  - use of metatables to emulate 64-bit bit operations and manipulation
  - uses strings to remove input already processed.

The first one means on every single bitwise operation, it is going to trigger a meta event. The second one means a lot of string copying around after every hash round iteration since Lua strings are interned and immutable.

Both of these things taken together means lua-hashing's performance is quadratic-like dog slow especially as input gets larger. I am not being obtuse when I say lua-hashing is 50-100x slower than alternative lua implementations -- it's that bad. Certainly not something I would use in production.

**Comment by somesocks** [comment]
Hi @greatwolf @tst2005, I've sent you both an invitation to become collaborators =)

I haven't forgotten about this package, I'm afraid its just been a busy few years for me.  If you'd like to bring it back to life, I think setting up TravisCI would be a great next step.  Let me know if you'd like to publish a new rocks version as well, and I'll help out there

**Comment by greatwolf** [comment]
Will do. Thank you :+1:

**Comment by greatwolf** [comment]
While you're still here, can you enable travis-ci for lua-lockbox under your account? It shouldn't take more than a couple of clicks.
