### ISSUE TITLE
why require("lockbox").insecure()

### ISSUE THREAD

**Issue by huangting** [somesocks/lua-lockbox#27]
There is an error about require("lockbox").insecure() in ecb.lua,sha1....
i can't find lockbox.lua or any other lib.
why require("lockbox").insecure()?
i'm using lua 5.1.4

**Comment by greatwolf** [comment]
[Security Concerns](https://github.com/somesocks/lua-lockbox#security-concerns) in the readme explains it. You just need to have `require 'lockbox'.ALLOW_INSECURE = true` in your script.

**Comment by huangting** [comment]
Thank you very much~
i want to use cipher mode ecb , but why it is insercue? 
Is there any bugs in ecb?

**Comment by tst2005** [comment]
ECB is insecure by design, see [wikipedia](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#ECB).
If you use for security, use at least CBC or any more modern ciphers.
