### ISSUE TITLE
Request to become collaborator

### ISSUE THREAD

**Issue by evkornev** [somesocks/lua-lockbox#29]
Hi!
I have prepared some code to fix issue https://github.com/somesocks/lua-lockbox/issues/7 (lua linting problems)
how could I make a PR?

Many thanks
Evgeny

**Comment by greatwolf** [comment]
Yes please do.

**Comment by evgenykor** [comment]
Done

**Comment by somesocks** [comment]
Hi @evgenykor, I've added you as a collaborator, so you can directly manage issues or create PRs in this repo.  Looking forward to seeing your improvements :smile:
