### ISSUE TITLE
Release on LuaRocks

### ISSUE THREAD

**Issue by jirutka** [somesocks/lua-lockbox#3]
Could you please release this module on [LuaRocks](https://luarocks.org)?

**Comment by somesocks** [comment]
:+1:  I'm a bit busy this week, but I'll look into it soon.

**Comment by tst2005** [comment]
I started to make a rockspec to support luarocks.
But it will be cleaner if we git tag a version.
Preview with a tag "0.1" : https://github.com/tst2005/lua-lockbox/tree/luarocks-support/rockspecs
