### ISSUE TITLE
Function table.maxn has been removed in Lua 5.3

### ISSUE THREAD

**Issue by jirutka** [somesocks/lua-lockbox#8]
http://www.lua.org/manual/5.2/manual.html#8.2:

> Function `table.maxn` is deprecated. Write it in Lua if you really need it.

As you can see [here](https://travis-ci.org/jirutka/lua-lockbox/jobs/91712460#L139-L173) in Travis log, it fails on this when running on Lua 5.3.

**Comment by somesocks** [comment]
Hmm, I suppose its not needed, but I preferred it over # due to the slightly different meanings.  Changed to # and pushed.
